platform :ios, '8.0'
use_frameworks!

target 'GrainDepot' do
    
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'SDCycleScrollView'
  pod 'YYModel'
  pod 'MBProgressHUD'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


